### ISSUE TITLE
[Protocol] Potential log in security issue

### ISSUE THREAD

**Issue by matthilde** [PintoIM/Pinto#12]
I think that the client-side LOGIN packet causes potential security problems.
Because it's good to use hashes to store passwords but if the client sends the hash directly it does not really make any sense.
+ The PintoServer stores this same hash as well. If the database content gets leaked, passwords are not preserved at all. The attacker can just use the hash to log in without problem.

**Comment by vlOd2** [comment]
Mind providing a solution to this problem?
I was thinking of re-hashing the hash with a salt, but the attacker can just re-hash as well

**Comment by vlOd2** [comment]
There is really not a solution to this issue, because it isn't an issue, I did add some checks to make sure it is a sha256 hash, and also fixed the SQL injection

If the database were to get leaked, obiously you could login into any account, so this is not an issue at all
