### ISSUE TITLE
Pinto Experimental server error

### ISSUE THREAD

**Issue by iamatsomeone** [PintoIM/Pinto#22]
Pinto experimental has version exp0 (note 0), so it bugs out and says the following:

![Must be 16, but got 0.](https://github.com/PintoIM/Pinto/assets/101672272/dedaa934-24b9-4930-8887-60a33d52a7b4)

**Comment by DexrnZacAttack** [comment]
I believe he changed the PintoServer and Pinto experimental clients to use 0 since it is a new branch, and you are trying to join a server that isnt updated to the experimental branch.

@vlOd2 please confirm

**Comment by vlOd2** [comment]
Pinto! EXP0 has not been officially release, you downloaded the latest commit which has no release, it is to be expected that the official server is not supporting the client, it is currently in-development, the server software also got a commit and you can build and you can host your own to test it

@DexrnZacAttack The network PVN was reset to 0, all versions from now will have that

**Comment by iamatsomeone** [comment]
> Pinto! EXP0 has not been officially release, you downloaded the latest commit which has no release, it is to be expected that the official server is not supporting the client, it is currently in-development, the server software also got a commit and you can build and you can host your own to test it

thanks for the info
