### ISSUE TITLE
Make the client also send packet shrimp to the server.

### ISSUE THREAD

**Issue by DexrnZacAttack** [PintoIM/Pinto#26]
## Is your feature request related to a problem? Please describe.
Yes, as sometimes you can get crashed or disconnected in some way that will cause your account to not disconnect from the server.

## Describe the solution you'd like
Make the client also send packet shrimp to the server to check if the client is still up, and make the server expect these packets or it will disconnect the user after a certain amount of missed packets.

**Comment by vlOd2** [comment]
This has been added
