### ISSUE TITLE
Pinto! crashes when you try to add a contact after getting kicked or disconnected

### ISSUE THREAD

**Issue by DexrnZacAttack** [PintoIM/Pinto#28]
## Describe the bug
If you try to add a contact when you are not on the server (e.g disconnected or kicked), Pinto! will crash.

## To Reproduce
1. Boot up a Pinto! server
2. Login and go to the add friend prompt, then type a name
3. Kick yourself from the server or cause some kind of disconnect
4. Press add

## Expected behavior
An error saying that you are not connected to the server, or something related, even if it is just making the prompt close and preventing the crash.

## Desktop (please complete the following information):
- OS: Windows 10
- Pinto! Version: exp1-hotfix1

**Comment by vlOd2** [comment]
Issue has been solved
