### ISSUE TITLE
Contact requests and messages while offline

### ISSUE THREAD

**Issue by DexrnZacAttack** [PintoIM/Pinto#29]
## Describe the solution you'd like
I would like a way that allows messages and contact requests to be received the next time a user logs on if any are received while the user is offline

## Describe alternatives you've considered
staying online all the time, but it wont work well if the computer is off

**Comment by vlOd2** [comment]
Messages won't be done, only contacts

**Comment by vlOd2** [comment]
Offline contact requests have been implemented
