### ISSUE TITLE
Chat messages save in different folder even if you connected to the same server using IP instead of domain

### ISSUE THREAD

**Issue by DexrnZacAttack** [PintoIM/Pinto#31]
## Describe the bug
If you connect to a server (e.g Ponso00.com from the server list, which will use an IP instead of domain) that is an IP, and then connect to the same server but it is a domain linking to that IP, the chat messages will not sync.

## To Reproduce
1. Connect to ponso00.com
2. Send some messages
3. Log out
4. Go to the server list and connect to the official server (which is ponso00.com but in IP form)
5. Try to send messages to the same person, the messages from ponso00 will be gone.

## Expected behavior
The messages should save between domain and IP if they are both the same.
Instead of storing using the server that was connected to as the folder, resolve the IP and use that as the folder for saving chat messages.

## Screenshots
This one has no messages, since i connected to ponso00 using IP address (from the server list)
![image](https://github.com/PintoIM/Pinto/assets/60078656/067e7ce5-a8f7-4c81-a9f1-ff120b6beb59)
This one does have messages since I connected using ponso00.com
![image](https://github.com/PintoIM/Pinto/assets/60078656/4296f92e-ce25-4766-a8f4-0d8085baf59e)

## Desktop (please complete the following information):
- OS: Windows 10
- Pinto! Version: exp1-hotfix1

**Comment by vlOd2** [comment]
This issue has been fixed
