### ISSUE TITLE
Credentials don't save after register

### ISSUE THREAD

**Issue by DexrnZacAttack** [PintoIM/Pinto#33]
## Describe the bug
When you register, the credentials are not saved, requiring you to enter them again when trying to login.

## To Reproduce
1. Register on a server
2. Log out
3. Try to login again, you will have to enter a username and password.

## Expected behavior
The credentials should save once you register.

## Desktop (please complete the following information):
- OS: Windows 10
- Pinto! Version: exp1-hotfix1

**Comment by vlOd2** [comment]
This is intended behaviour
