### ISSUE TITLE
Make messages merge better (like discord)

### ISSUE THREAD

**Issue by DexrnZacAttack** [PintoIM/Pinto#34]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
I apologize about the title being vague, I don't know how to phrase it well, so I will do it in here.

I would like it so that when you text someone, instead of the name sending everytime you message, make it only show when required (e.g someone sent a message after your last message or it has been 1 minute since your last message)

## Additional context
I am talking about the name that is shown when you message
![image](https://github.com/PintoIM/Pinto/assets/60078656/26dc9f3c-1071-45fc-ab69-e0bcac26045f)
I want it to work like Discord, where the messages merge if possible.
![image](https://github.com/PintoIM/Pinto/assets/60078656/aab74e5d-9af6-4028-97f8-864b4cbeaaba)

**Comment by vlOd2** [comment]
This is a good feature, except that IM clients during these days, had instant messaging in an IRC style not the style you said, so this is a no due to the goal of Pinto!, also the implementation would likely introduce a lot of bugs too and make chatting frustrating
