### ISSUE TITLE
Add statuses to pinto + music integration

### ISSUE THREAD

**Issue by DexrnZacAttack** [PintoIM/Pinto#35]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
Add statuses to pinto, as well as adding Windows Media Player (and maybe VLC) integration, and show that song as your status. 
Just like Windows Live Messenger (or is it Escargot)

**Comment by vlOd2** [comment]
> Just like Windows Live Messenger (or is it Escargot)
WLM, Escargot didn't do anything to the client, they just made a server for it

**Comment by vlOd2** [comment]
This is a good idea

**Comment by TheAwesome98-Real** [comment]
and spotify, but i don't know if there's an sdk or something or if it costs money

**Comment by vlOd2** [comment]
It seems like this is not really possible for Windows Media Player and VLC

For WMP you need to register a COM library in-order to be able to get the current song, and this is not very easy to do in C#, let alone to not need admin privilleges and keep Linux compatibility

For VLC, you need to make a Lua extension and keep a HTTP server constantly running (Lua extensions in VLC require you to have the VLC HTTP webinterface server running)
