### ISSUE TITLE
pinto client scrolls to the wrong area when a message is sent or received

### ISSUE THREAD

**Issue by TheAwesome98-Real** [PintoIM/Pinto#44]
## Describe the bug
if you send or receive a message the pinto client scrolls to the middle of the area instead of the bottom. linux/wine issue?

## To Reproduce
1. open pinto
2. log on
3. go to an added contact who has a lot of messages
4. message them
5. you will get scrolled to the middle for some reason

## Expected behavior
it should scroll to the very bottom instead

## Screenshots
not really applicable but if you want then ask

## Desktop (please complete the following information):
- OS: [e.x. Windows 10] Ubuntu GNU/Linux 22.04.2 LTS
- Pinto! Version: [e.x. exp1-hotfix1] exp1-hotfix1

## Additional context
i use linux btw

**Comment by vlOd2** [comment]
Further testing suggested this is an issue with mono (which is what wine uses for .NET assemblies)
It appears to be something of not being able to keep up
