### ISSUE TITLE
White chat when opening it after receiving a message in it

### ISSUE THREAD

**Issue by ghost** [PintoIM/Pinto#45]
## Describe the bug
When I receive a message in a chat that was minimized, when I open it, all the text is white until I send a message or scroll.

## To Reproduce
1. Keep a chat window minimized
2. Receive a message in it
3. Open the chat window (from taskbar)

## Expected behavior
All the messages should appear as they are supposed to.

## Screenshots
![White chat](https://i.imgur.com/gJzaBOW.png)

- OS: Windows 10
- Version: exp1-hotfix1

**Comment by unnaturalistic** [comment]
IM FAMOUS!

**Comment by vlOd2** [comment]
This should've been fixed now, if it still occurs, try submitting the report again
