### ISSUE TITLE
"Forgot your Password" link gets enabled after choosing "I would like to create a new Pinto account"

### ISSUE THREAD

**Issue by jonnyprogamer** [PintoIM/Pinto#47]
## Describe the bug
The "Forgot your Password" link in the UsingPintoForm gets enabled after choosing "Sign-Up for a new account" and switching back to "I already have a Pinto account"

## To Reproduce
1. Press "Click here to log in"
2. Click on "I would like to create a new Pinto account"
3. Click on "I already have a Pinto account"
5. See error

## Expected behavior
The link remains disabled even after choosing the other option

## Screenshots
![image](https://github.com/PintoIM/Pinto/assets/93492418/cf3b2d37-7885-4faa-8228-b8771f1df4cc)

## Desktop (please complete the following information):
- OS: Windows 7
- Pinto! Version: beta1.0

## Additional context
None

**Comment by vlOd2** [comment]
Fixed
