### ISSUE TITLE
Pinto downloading 32-bit version of an update instead of 64-bit when using SETUP

### ISSUE THREAD

**Issue by unnaturalistic** [PintoIM/Pinto#49]
## Describe the bug
Pinto is downloading a 32 bit version of an update instead of the system default of 64 bit

## To Reproduce
1. launch pinto
2. wait for update screen
3. try to update
4. wait until update file is downloaded

## Expected behavior
Pinto getting updated

## Desktop
- OS: Windows 10 64 bit
- Pinto! Version: `Any version that can download updates`

## Logs:
```
System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at PintoNS.MainForm.<<CheckForUpdates>b__42_0>d.MoveNext() in D:\dev\C#\Pinto\Pinto\MainForm.cs:line 590
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state
```

**Comment by vlOd2** [comment]
This is not because of the architecture, first of Pinto! releases are always x86, second, you are on the b1.0-pre1 release which is not marked as latest (and still downloads the legacy installer) and has a different installer

This is not an issue, just the fact that you are using pre builds
