### ISSUE TITLE
Remote Host when calling? what is that

### ISSUE THREAD

**Issue by weegeer** [PintoIM/Pinto#50]
i found the feature to call but what is remote host? what do i put in there
![Immagine 2023-06-22 180602](https://github.com/PintoIM/Pinto/assets/137427565/5a12ee34-8320-42ca-acc4-449f50cbc1f2)

**Comment by DexrnZacAttack** [comment]
I believe you need to enter the IP Address of the person you wish to call.

**Comment by toastytoaster35** [comment]
i tried with my friends ip but it doesnt work

**Comment by jonnyprogamer** [comment]
> i tried with my friends ip but it doesnt work

Yes you need to put your friend IP, but you (and your friend) must make sure that UPNP is enabled in your Modem (and also in your Router if you have one)

**Comment by toastytoaster35** [comment]
i have an italian router and who tf uses modems today its for dial up only

**Comment by toastytoaster35** [comment]
> 

i just dont know how to enable upnp

UPDATE: i found a solution to enable upnp

**Comment by jonnyprogamer** [comment]
> i have an italian router and who tf uses modems today its for dial up only

Im also in italy, and no, the modem is the box you connect to the wall for internet, the router is an additional box that you connect to the modem to get more Ethernet ports / more Wi-Fi coverage.

**Comment by jonnyprogamer** [comment]
> > 
> UPDATE: i found a solution to enable upnp

👍

**Comment by vlOd2** [comment]
@weegeer Sorry for the confusion, the current system isn't perfect but to establish a call, you must do the following steps:
1. You and your buddy select their audio preferences
2. Make sure you and your buddy have UPnP enabled or have both opened the UDP port 65413
3. You enter you buddy's IP and your buddy enters your IP
4. You both click "Start"

If you did everything correctly, you should start being able to talk

**Comment by vlOd2** [comment]
If you have any more issues, comment them here, but I answered what the question was
