### ISSUE TITLE
Server list is down

### ISSUE THREAD

**Issue by DexrnZacAttack** [PintoIM/Pinto#51]
## Describe the bug
api.fieme.net is down.

## To Reproduce
1. Go to server list

## Expected behavior
it should show the server list

## Screenshots
![image](https://github.com/PintoIM/Pinto/assets/60078656/789bcf62-f7b5-4a75-b100-3a701e731653)

## Desktop (please complete the following information):
- OS: Windows 10
- Pinto! Version: any version with server list, i tested on latest experimental and latest beta

**Comment by toastytoaster35** [comment]
the server list doesnt work somehow even if i login with my pinto account (latest pinto no beta)

**Comment by vlOd2** [comment]
The server list domain is no longer available
