### ISSUE TITLE
not being able to log in

### ISSUE THREAD

**Issue by reprovision** [PintoIM/Pinto#58]
when i log in it gives me a error

Expected behavior:
i expected it to log in

no screenshots cuz my pc is trash

- OS: WIndows 11
- Pinto! Version: Beta 1.1

heres the error log:
```NAudio.MmException: BadDeviceId calling waveInOpen
   at System.Runtime.CompilerServices.AsyncServices.<ThrowAsync>b__0(Object state)```

**Comment by reprovision** [comment]
the error logs not working so
NAudio.MmException: BadDeviceId calling waveInOpen
   at System.Runtime.CompilerServices.AsyncServices.<ThrowAsync>b__0(Object state)

**Comment by vlOd2** [comment]
Appears to be happening due to no microphones being picked up....
Try plugging a microphone in, or atleast install a virtual one and try again

**Comment by reprovision** [comment]
ok illtry

**Comment by reprovision** [comment]
okie ye thanks that worked
