### ISSUE TITLE
Don't open console at start

### ISSUE THREAD

**Issue by giovannirizzello** [PintoIM/Pinto#70]
Feature to not open console at startup?
And auto login would be perfect
(discord link dead btw)

**Comment by vlOd2** [comment]
Auto login is planned for b1.2
Console opening at start-up will be addressed in close to launch, as it is necessary to indicate to the user that it's there so issues could be reported accurately
> (discord link dead btw)
There wasn't one anywhere here

**Comment by giovannirizzello** [comment]
Thank you
For discord I meant this link
![image](https://github.com/PintoIM/Pinto/assets/113061484/9c5ec1d1-38eb-4a10-b14e-469ece225577)
in the welcome dialog

**Comment by vlOd2** [comment]
The welcome dialog has been removed in b1.2
